######################################################################
# Automatically generated by qmake (3.0) Sat Mar 17 14:24:56 2018
######################################################################

TEMPLATE = subdirs

# Directories
SUBDIRS += learnopengl.pro opengllearning.pro
